name: build
on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build and deploy to App store connect
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
      - name: Install Flutter Package
        run: flutter pub get
      - name: Install pods
        run: cd ios && pod install
      - name: Build iOS bundle
        run: flutter build ios --release --no-codesign
      - name: Export ipa
        run: flutter build ipa --export-method "app-store" --release

      - name: Upload to App Store Connect
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{secrets.APP_STORE_CONNECT_ISSUE_ID}}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          xcrun altool --upload-app -t ios -f build/ios/ipa/app.ipa --apikey "$APP_STORE_CONNECT_PRIVATE_KEY" --issueId "$APP_STORE_CONNECT_ISSUER_ID" --apiIssuer "$APP_STORE_CONNECT_KEY_IDENTIFIER"
