name: Check and test source code
on:
  pull_request:
    branches:
      - release
jobs:
  test:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.19.0'
      - name: Install Packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test